
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8


spring:
  # 激活哪一个环境的配置文件
  profiles:
    active: ${ACTIVE_ENV:fz}
    # 服务名称
  application:
    name: halo-project
  jackson:
    default-property-inclusion: non_null # 全局jackson配置
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


# 配置nacos
#  cloud:
#    nacos:
#      config:
#        group: HALO_GROUP
#        file-extension: yaml
#        extension-configs:
          # 指定去读哪个组下的哪个配置文件，refresh：是否支持实时生效
#          - {data-id: "halo-project.yaml", group: HALO_GROUP, refresh: false}
#          - {data-id: "halo_resource.yml", group: HALO_GROUP, refresh: false}
#          - {data-id: "halo_common.yml", group: HALO_GROUP, refresh: true}
  config:
    import:
      - nacos:halo_resource.yml?group=HALO_GROUP&refresh=true
      - nacos:halo_common.yml?group=HALO_GROUP&refresh=true










